### ISSUE TITLE
Enhancement to display correct question text on recap for checkbox and multiple choice

### ISSUE THREAD

**Issue by nicovanniekerk** [proversity-org/recap-xblock#52]
@lidijarad a request from the LD team  is to change the text being pulled into the recap tool from the checkbox and multiple choice problems, from the text inside the problem, to the display name of the problem.

image as example.
![image](https://user-images.githubusercontent.com/3447257/36139137-172778fe-10a5-11e8-8cf2-de7fdd6d213f.png)

**Comment by mariushuman** [comment]
@lidijarad , can you also please look at the following issue.

When creating a recap section and want to add Free text response unique number by clicking on Add problem, nothings happens.

Steps:
1.  Select a free text advance problem type
2.  Select a Recap advance problem type
3.  Go the Free text unit and copy the unique number and close the window
4.  Go to the Recap section and click Add problem type

Results:
Nothing happanes and the user cannot add the ubique number

Expected Results:
The user is able to add the unique number and save it

**Comment by lidijarad** [comment]
@nicovanniekerk @mariushuman, thank you. I am looking into this and will fix this ASAP.

**Comment by nicovanniekerk** [comment]
@lidijarad thanks for this fix. closing this.

@mariushuman FYI: this needs an extra enhancement to allow this stuff to be downloaded in the recap section of the instructor dashboard. please make sure there is ticket.
