### ISSUE TITLE
Recap Export have english text in arabic course

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/recap-xblock#56]
When a recap section is downloaded from the Instructor dashboard, the answer that were left blank, display 'None ' in the download file.

url: https://khda.proversity.org/courses/course-v1:KHD+KHD001Arabic+2017_T4/instructor#view-recap

Steps.
1.  Click on the url and login
2.  Select you the language to arabic
3.  Click on the Instructors tab and select Recap
4.  Select the student (Marius) and download his recap answer sheet and open it.

Results
All the left out questions display None. 

Expected results 
The left out questions should display NONE in Arabic. 

[6_3_2018_MariusHuman (4).pdf](https://github.com/proversity-org/recap-xblock/files/1783747/6_3_2018_MariusHuman.4.pdf)

**Comment by lidijarad** [comment]
@nicovanniekerk, all translations have been completed by you. I am closing this issue.
