### ISSUE TITLE
Export recap xblock translations for Lilla

### ISSUE THREAD

**Issue by renevatium** [proversity-org/recap-xblock#60]
Lilla needs to send off for French translations. Please export the translations. Preferably into a csv if possible. You can convert django translation files to other formats using [this](http://docs.translatehouse.org/projects/translate-toolkit/en/latest/index.html).

**Comment by nicovanniekerk** [comment]
Translation files generated and sent off, PS: there is a enhancement made for the table on the instructor dashboard to translate the table headings, this has a PR waiting to be merged.
